version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/postgres:/data/db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  mongo:
    image: mongo
    volumes:
      - ./tmp/mongo:/data/db
    ports:
      - "27017:27017"
